BASE_LOCATION: ${user.dir}
DB_NAME: blog



server:
  port: 8888


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/${DB_NAME}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
